-- MySQL Script generated by MySQL Workbench
-- 11/03/17 23:20:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jobfinder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jobfinder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobfinder` DEFAULT CHARACTER SET utf8 ;
USE `jobfinder` ;

-- -----------------------------------------------------
-- Table `jobfinder`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobfinder`.`users` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `surname` VARCHAR(128) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `city` VARCHAR(128) NOT NULL,
  `province` VARCHAR(2) NOT NULL,
  `telnumber` VARCHAR(13) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `study` VARCHAR(128) NOT NULL,
  `curriculum` VARCHAR(1024) NULL,
  `image` VARCHAR(255) NOT NULL,
  `birthdate` VARCHAR(12) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobfinder`.`businessusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobfinder`.`businessusers` (
  `idbusinessuser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `surname` VARCHAR(128) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `birthdate` VARCHAR(12) NOT NULL,
  `telnumber` VARCHAR(13) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `businessname` VARCHAR(255) NOT NULL,
  `businesstype` VARCHAR(128) NOT NULL,
  `businesscity` VARCHAR(128) NOT NULL,
  `businessprov` VARCHAR(2) NOT NULL,
  `businessaddress` VARCHAR(255) NOT NULL,
  `businessdescription` VARCHAR(1024),
  `image` VARCHAR(255) NOT NULL,
  `lat` FLOAT NOT NULL,
  `lng` FLOAT NOT NULL,
  PRIMARY KEY (`idbusinessuser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `lat_UNIQUE` (`lat` ASC),
  UNIQUE INDEX `lng_UNIQUE` (`lng` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobfinder`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobfinder`.`skills` (
  `idskill` INT NOT NULL AUTO_INCREMENT,
  `profession` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idskill`),
  UNIQUE INDEX `profession_UNIQUE` (`profession` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobfinder`.`jobads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobfinder`.`jobads` (
  `idjobad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `businessuser_idbusinessuser` INT UNSIGNED NOT NULL,
  `numpositions` INT UNSIGNED NOT NULL,
  `cash` FLOAT NOT NULL,
  `initperiod` VARCHAR(24) NOT NULL,
  `endperiod` VARCHAR(24) NOT NULL,
  `initday` VARCHAR(24) NOT NULL,
  `endday` VARCHAR(24) NOT NULL,
  `inittime` VARCHAR(24) NOT NULL,
  `endtime` VARCHAR(24) NOT NULL,
  `extra` TINYINT(1) NOT NULL,
  `expired` TINYINT(1) NOT NULL,
  `insertdate` DATE NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `jobtype` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idjobad`),
  INDEX `fk_jobad_businessuser1_idx` (`businessuser_idbusinessuser` ASC),
  CONSTRAINT `fk_jobad_businessuser1`
    FOREIGN KEY (`businessuser_idbusinessuser`)
    REFERENCES `jobfinder`.`businessusers` (`idbusinessuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobfinder`.`jobrequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobfinder`.`jobrequests` (
  `user_iduser` INT UNSIGNED NOT NULL,
  `jobad_idjobad` INT UNSIGNED NOT NULL,
  `reply` VARCHAR(16) NOT NULL,
  `requestdate` DATE NOT NULL,
  PRIMARY KEY (`user_iduser`, `jobad_idjobad`),
  INDEX `fk_user_has_jobad_jobad1_idx` (`jobad_idjobad` ASC),
  INDEX `fk_user_has_jobad_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_jobad_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `jobfinder`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_jobad_jobad1`
    FOREIGN KEY (`jobad_idjobad`)
    REFERENCES `jobfinder`.`jobads` (`idjobad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobfinder`.`user_has_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobfinder`.`user_has_skill` (
  `user_iduser` INT UNSIGNED NOT NULL,
  `skill_idskill` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `skill_idskill`),
  INDEX `fk_user_has_skill_skill1_idx` (`skill_idskill` ASC),
  INDEX `fk_user_has_skill_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_skill_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `jobfinder`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_skill_skill1`
    FOREIGN KEY (`skill_idskill`)
    REFERENCES `jobfinder`.`skills` (`idskill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobfinder`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobfinder`.`sessions` (
  `idsession` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `businessusers_idbusinessuser` INT UNSIGNED NULL,
  `users_iduser` INT UNSIGNED NULL,
  PRIMARY KEY (`idsession`),
  INDEX `fk_sessions_businessusers1_idx` (`businessusers_idbusinessuser` ASC),
  INDEX `fk_sessions_users1_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_sessions_businessusers1`
    FOREIGN KEY (`businessusers_idbusinessuser`)
    REFERENCES `jobfinder`.`businessusers` (`idbusinessuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `jobfinder`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
